[project]
name = "exp_0002_google_genai"
version = "0.0.0"
requires-python = "==3.13.7.*"
dependencies = [
  "google-genai>=1.73.1",
  "pillow>=12.2",
  "pydantic",
  "pymupdf",
  "py-lib-testkit",
  "tenacity>=9.1.4",
]

[dependency-groups]
report = [
  "ipykernel>=7.3",
]

[tool.uv]
required-version = "==0.12.5"
sources.py-lib-testkit = { git = "https://github.com/betabitplus/ternforge-tooling-py-testkit.git", tag = "v2.2.2" }
